# Gradle
org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=false
# Loom
fabric.loom.multiProjectOptimisation=true
# Mod Metadata
group=io.github.afamiliarquiet
user=afamiliarquiet
slug=be-a-doll
modId=be_a_doll
modName=Would you be a doll?
modDescription=A small Toybox mod - become the toy, become a doll!
authors=afamiliarquiet
contributors=
license=MIT
# Mod Version
modVersion=1.0.10
# Branch Metadata
branchName=fabric-26.2
compatibleVersions=26.2
compatibleLoaders=fabric

loom_version = 1.17-SNAPSHOT
