[versions]
loom = "1.17-SNAPSHOT"
minotaur = "2.+"

mc = "26.2"
fl = "0.19.3"
fapi = "0.154.0+26.2"

[plugins]
loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }

[libraries]
mc = { group = "com.mojang", name = "minecraft", version.ref = "mc" }
fl = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fl" }
fapi = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fapi" }
